version: '3'
services:
  frontend:
    container_name: cfy_client
    build:
      context: './frontend'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - mern-stack-network
    depends_on:
      - backend
  
  backend:
    container_name: cfy_server
    build:
      context: './backend'
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - mern-stack-network
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-container
    networks:
      - mern-stack-network
    volumes:
      - mongoData:/data/db
    
      
networks:
  mern-stack-network:
volumes:
  mongoData: