apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: workshop
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/wededo4644/workout_frontend:65
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://api:4000/api/workouts" 
        ports:
        - containerPort: 3000